name: Expressions Implementation

on: push

env:
  appName: CounterApp

jobs:
  build_job:
    runs-on: windows-latest
    steps:
      - name: Cache
        uses: actions/cache@v1.2.1
        with:
          path: .
          key: "artifact"
          restore-keys: "" # optional
